config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :badges
    resource :theme, only: [:update, :show]
  end
end

app/controllers/spree/admin/themes_controller.rb
module Spree
  module Admin
    class ThemesController < Spree::Admin::BaseController

      def update
        Spree::Config[:theme_name] = params[:theme][:name]
        redirect_to action: :show
      end

    end
  end
end

app/helpers/spree/admin/themes_helper.rb
module Spree
  module Admin
    module ThemesHelper
      def available_themes
        @available_themes ||=  Dir.human_entries(Rails.root.join('vendor', 'themes'))
        unless @available_themes.include?('default')
          @available_themes.push('default')
        end
        @available_themes
      end
    end
  end
end

app/views/spree/admin/themes/show.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:theme) %>
<% end %>

<h4><%= "Current theme - #{ Spree::Config[:theme_name] }" %></h4>


<%= form_tag admin_theme_path, method: :patch do %>
  <div class="panel panel-default" data-hook="tax_rates">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= Spree.t(:select_new_theme) %>
      </h1>
    </div>

    <div class="panel-body">
      <div class="col-md-6">
        <div data-hook="name" class="form-group">
          <%= select :theme, :name, available_themes, { selected: Spree::Config[:theme_name] }, class: 'form-control select' %>
        </div>
      </div>
    </div>

  </div>
  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'refresh', 'submit', {class: 'btn-success'} %>
  </div>

<% end %>