config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :badges
    resource :theme, only: [:update, :show]
  end
end

app/models/spree/badge.rb
module Spree
  class Badge < ActiveRecord::Base
    has_many :products, class_name: 'Spree::Product'

    validates :name, presence: true
  end
end

app/controllers/spree/admin/badges_controller.rb
module Spree
  module Admin
    class BadgesController < Spree::Admin::ResourceController
    end
  end
end

app/views/spree/admin/badges/_form.html.erb
<div data-hook="admin_badge_form_fields" class="row">
  <div class="col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name, :class => 'form-control' %>
    <% end %>
  </div>
</div>

app/views/spree/admin/badges/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::Badge.model_name.human) %> / <%= @badge.name %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @badge } %>

<%= form_for [:admin, @badge] do |f| %>
  <fieldset>
    <%= render 'form', f: f %>
    <%= render 'spree/admin/shared/edit_resource_links', collection_url: admin_badges_path %>
  </fieldset>
<% end %>

app/views/spree/admin/badges/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Badge) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_badge), new_admin_badge_url(@badge), { class: "btn-success", icon: 'add', id: 'new_badge_link' } %>
<% end if can? :create, Spree::Badge %>

<div id="badge-list" data-hook>
  <table class="table" id='listing_badges' data-hook>
    <thead>
      <tr data-hook="badges_header">
        <th><%= Spree.t(:name) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @badges.each do |badge| %>
        <tr id="<%= spree_dom_id badge %>" data-hook="states_row">
          <td><%= badge.name %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit_url(edit_admin_badge_url(badge), :no_text => true) if can? :edit, badge %>
          </td>
        </tr>
      <% end %>
      <% if @badges.empty? %>
        <tr><td colspan="3"><%= Spree.t(:none) %></td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spree/admin/badges/new.html.erb
<%= render :partial => 'spree/admin/shared/error_messages', locals: { target: @badge } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_badge) %>
<% end %>

<%= form_for [:admin, @badge] do |f| %>
  <fieldset>
    <%= render 'form', { f: f } %>
    <%= render 'spree/admin/shared/new_resource_links', collection_url: admin_badges_path %>
  </fieldset>
<% end %>